import { defineNuxtPlugin } from '#app';
import PrimeVue from 'primevue/config';
import InputText from 'primevue/inputtext';
import InputSwitch from 'primevue/inputswitch';
import InputMask from 'primevue/inputmask';
import Password from 'primevue/password';
import Dropdown from 'primevue/dropdown';
import FileUpload from 'primevue/fileupload';
import Button from 'primevue/button';
import Checkbox from 'primevue/checkbox';
import TreeSelect from 'primevue/treeselect';
import Chart from 'primevue/chart';
import Dialog from 'primevue/dialog';
import Textarea from 'primevue/textarea';
import CascadeSelect from 'primevue/cascadeselect';
import Paginator from 'primevue/paginator';
import Toast from 'primevue/toast';
import ToastService from 'primevue/toastservice';
import Skeleton from 'primevue/skeleton';
import Menu from 'primevue/menu';
import TieredMenu from 'primevue/tieredmenu';
import Listbox from 'primevue/listbox';
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';
import ProgressSpinner from 'primevue/progressspinner';
import InputNumber from 'primevue/inputnumber';
import Galleria from 'primevue/galleria';
import ColorPicker from 'primevue/colorpicker';
import MultiSelect from 'primevue/multiselect';
import PanelMenu from 'primevue/panelmenu';
import Calendar from 'primevue/calendar';

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(PrimeVue, { ripple: true });
  nuxtApp.vueApp.component('InputText', InputText);
  nuxtApp.vueApp.component('InputMask', InputMask);
  nuxtApp.vueApp.component('Password', Password);
  nuxtApp.vueApp.component('Dropdown', Dropdown);
  nuxtApp.vueApp.component('FileUpload', FileUpload);
  nuxtApp.vueApp.component('Button', Button);
  nuxtApp.vueApp.component('Checkbox', Checkbox);
  nuxtApp.vueApp.component('TreeSelect', TreeSelect);
  nuxtApp.vueApp.component('Chart', Chart);
  nuxtApp.vueApp.component('Dialog', Dialog);
  nuxtApp.vueApp.component('Textarea', Textarea);
  nuxtApp.vueApp.component('InputSwitch', InputSwitch);
  nuxtApp.vueApp.component('CascadeSelect', CascadeSelect);
  nuxtApp.vueApp.component('Paginator', Paginator);
  nuxtApp.vueApp.component('MultiSelect', MultiSelect);
  nuxtApp.vueApp.component('Toast', Toast);
  nuxtApp.vueApp.use(ToastService);
  nuxtApp.vueApp.component('Skeleton', Skeleton);
  nuxtApp.vueApp.component('Menu', Menu);
  nuxtApp.vueApp.component('TieredMenu', TieredMenu);
  nuxtApp.vueApp.component('Listbox', Listbox);
  nuxtApp.vueApp.component('DataTable', DataTable);
  nuxtApp.vueApp.component('Column', Column);
  nuxtApp.vueApp.component('ProgressSpinner', ProgressSpinner);
  nuxtApp.vueApp.component('InputNumber', InputNumber);
  nuxtApp.vueApp.component('Galleria', Galleria);
  nuxtApp.vueApp.component('ColorPicker', ColorPicker);
  nuxtApp.vueApp.component('PanelMenu', PanelMenu);
  nuxtApp.vueApp.component('Calendar', Calendar);
  //other components that you need
});
